# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "*" ]
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  main-branch-integration:
    runs-on: self-hosted
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'create' && startsWith(github.ref, 'refs/tags')) }}
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        export CONDA_HOME=/opt/miniconda3
        . "$CONDA_HOME/etc/profile.d/conda.sh"
        conda activate bio
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip uninstall gpm --yes
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install .
    - name: Lint with flake8
      run: |
        export CONDA_HOME=/opt/miniconda3
        . "$CONDA_HOME/etc/profile.d/conda.sh"
        conda activate bio
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        export CONDA_HOME=/opt/miniconda3
        . "$CONDA_HOME/etc/profile.d/conda.sh"
        conda activate bio
        pytest
    - name: Re install 'main' branch in case of failure
      if: failure()
      run: |
        export CONDA_HOME=/opt/miniconda3
        . "$CONDA_HOME/etc/profile.d/conda.sh"
        conda activate bio
        pip uninstall gpm --yes 
        git fetch
        git checkout origin/main
        python -m pip install --upgrade pip
        pip install . -r requirements.txt
    
  test-development-branch:  
    runs-on: self-hosted
    if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main'}}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        export CONDA_HOME=/opt/miniconda3
        . "$CONDA_HOME/etc/profile.d/conda.sh"
        conda activate bio_test
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip uninstall gpm --yes
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install .
    - name: Lint with flake8
      run: |
        export CONDA_HOME=/opt/miniconda3
        . "$CONDA_HOME/etc/profile.d/conda.sh"
        conda activate bio_test
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        export CONDA_HOME=/opt/miniconda3
        . "$CONDA_HOME/etc/profile.d/conda.sh"
        conda activate bio_test
        pytest
    - name: Re install 'main' branch in case of failure
      if: failure()
      run: |
        export CONDA_HOME=/opt/miniconda3
        . "$CONDA_HOME/etc/profile.d/conda.sh"
        conda activate bio_test
        pip uninstall gpm --yes 
        git fetch
        git checkout origin/main
        python -m pip install --upgrade pip
        pip install . -r requirements.txt
